apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knowledge-repo-ingress
  namespace: knowledge-repo
  labels:
    app: knowledge-repo
spec:
  ingressClassName: nginx
  rules:
    - host: api.knowledge-repo.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: knowledge-repo-server
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: knowledge-repo-client
                port:
                  number: 80
