apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-repo-db-data
  namespace: knowledge-repo
  labels:
    app: knowledge-repo-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
