apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-repo-client
  labels:
    app: knowledge-repo-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knowledge-repo-client
  template:
    metadata:
      labels:
        app: knowledge-repo-client
    spec:
      containers:
        - name: knowledge-repo-client
          image: knowledge-repo-client:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"